apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workflow-hello-world-ldap-chart.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "workflow-hello-world-ldap-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workflow-hello-world-ldap-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "workflow-hello-world-ldap-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: ldap
          image: {{ .Values.openldapImage.repository }}:{{ .Values.openldapImage.tag }}
          imagePullPolicy: {{ .Values.openldapImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: LDAP_INIT_ORG_DN
              value: {{ .Values.ldap.baseDN | quote }}
            - name: LDAP_INIT_ORG_NAME
              value: "Example, Inc"
            - name: LDAP_INIT_ROOT_USER_DN
              value: {{ .Values.ldap.adminUsername | quote }}
            - name: LDAP_INIT_ROOT_USER_PW
              value: {{ .Values.ldap.adminPassword | quote }}
            - name: LDAP_INIT_ALLOW_CONFIG_ACCESS
              value: "true"
          volumeMounts:
            - name: ldifs
              mountPath: /opt/ldifs/custom
          readinessProbe:
            exec:
              command:
                - ldapsearch
                - -x
                - -H
                - ldap://localhost:{{ .Values.service.targetPort }}
                - -D
                - {{ .Values.ldap.adminUsername }}
                - -w
                - {{ .Values.ldap.adminPassword }}
                - -b
                - {{ .Values.ldap.baseDN }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - ldapsearch
                - -x
                - -H
                - ldap://localhost:{{ .Values.service.targetPort }}
                - -D
                - {{ .Values.ldap.adminUsername }}
                - -w
                - {{ .Values.ldap.adminPassword }}
                - -b
                - {{ .Values.ldap.baseDN }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: ldifs
          configMap:
            name: {{ include "workflow-hello-world-ldap-chart.fullname" . }}-config-map