server:
  servlet:
    context-path: /bpm
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: workflow-hello-world

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:workflow-hello-world

  ldap:
    url: ldap://localhost:389
    base-dn: dc=example,dc=ch
    manager-dn: cn=admin,dc=example,dc=ch
    manager-password: password

  docker:
    compose:
      enabled: true
      stop:
        command: down
      skip:
        in-tests: false

camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: camunda-admin
    filter:
      create: All Tasks
    client:
      base-url: http://localhost:8081/${server.servlet.context-path}/engine-rest
      worker-id: spring-boot-worker
      basic-auth:
        username: camunda-admin
        password: camunda-admin-password
    metrics:
      enabled: true
      db-reporter-activate: true
    generic-properties:
      ignore-unknown-fields: false
      properties:
        javaSerializationFormatEnabled: true
        historyTimeToLive: 5
        enableExceptionsAfterUnhandledBpmnError: true

camunda-ldap-plugin:
  url: ldap://localhost:389
  sslEnabled: false
  user: cn=admin,dc=example,dc=ch
  password: password
  base-dn: dc=example,dc=ch
  users:
    user-search-base: "ou=users"
    user-search-filter: "(objectClass=inetOrgPerson)"
    user-id-attribute: uid
    user-firstname-attribute: givenName
    user-lastname-attribute: sn
    user-email-attribute: mail
    user-password-attribute: userPassword
  groups:
    group-search-base: "ou=groups"
    group-search-filter: "(objectClass=groupOfNames)"
    group-id-attribute: cn
    group-name-attribute: cn
    group-member-attribute: member
camunda-authorization-plugin:
  admin-group: "camunda-admins"
  admin-user: "camunda-admin"

management:
  health:
    ldap:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  show-actuator: true
  api-docs:
    path: /swagger/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    show-extensions: true

# logbook does not work with camunda
logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      # Exclude HTML-related calls and specific endpoints that Logbook doesn't handle correctly
      #- path: ${server.servlet.context-path}/actuator/health/**
      - path: ${server.servlet.context-path/h2-console/**  # Exclude H2 console
      - path: ${server.servlet.context-path/swagger-ui/**  # Exclude Swagger UI if used
      - path: ${server.servlet.context-path/v3/api-docs/** # Exclude OpenAPI docs if used
      - path: ${server.servlet.context-path/favicon.ico
      # Exclude HTML-related calls and web resources
      - path: ${server.servlet.context-path/**/*.html
      - path: ${server.servlet.context-path/**/*.css
      - path: ${server.servlet.context-path/**/*.js
      - path: ${server.servlet.context-path/**/*.png
      - path: ${server.servlet.context-path/**/*.jpg
      - path: ${server.servlet.context-path/**/*.jpeg
      - path: ${server.servlet.context-path/**/*.gif
      - path: ${server.servlet.context-path/**/*.ico
      - path: ${server.servlet.context-path/**/favicon.ico
      - path: ${server.servlet.context-path/**/webjars/**
      # Exclude other common web resources
      - path: ${server.servlet.context-path/**/assets/**
      - path: ${server.servlet.context-path/**/static/**
      - path: ${server.servlet.context-path/**/public/**
      - path: ${server.servlet.context-path/**/resources/**
      - path: ${server.servlet.context-path/webjars/**
      # Add more exclusions as needed

application:
  apifirst-server-jpa:
    protocol: "http"
    host: "localhost"
    port: "8082"
    context: "/"
