server.servlet.context-path: /bpm

camunda.bpm.admin-user:
  id: admin
  password: admin

camunda.bpm.metrics:
  enabled: false
  db-reporter-activate: false

camunda.bpm:
  generic-properties.properties:
    telemetry-reporter-activate: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  config: "classpath:logging/log4j2.xml"

springdoc:
  show-actuator: true
  api-docs:
    path: /swagger/v3/api-docs