spring:
  application:
    name: workflow-hello-world

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:workflow-hello-world

  docker:
    compose:
      enabled: true
      stop:
        command: down
      skip:
        in-tests: false

server:
  servlet:
    context-path: /bpm
  port: 8081

camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: camunda-admin
    filter:
      create: All Tasks
    metrics:
      enabled: true
      db-reporter-activate: true

camunda-ldap-plugin:
  url: ldap://localhost:389
  sslEnabled: false
  user: cn=admin,dc=example,dc=ch
  password: password
  base-dn: dc=example,dc=ch
  users:
    user-search-base: "ou=users"
    user-search-filter: "(objectClass=inetOrgPerson)"
    user-id-attribute: uid
    user-firstname-attribute: givenName
    user-lastname-attribute: sn
    user-email-attribute: mail
    user-password-attribute: userPassword
  groups:
    group-search-base: "ou=groups"
    group-search-filter: "(objectClass=groupOfNames)"
    group-id-attribute: cn
    group-name-attribute: cn
    group-member-attribute: member
camunda-authorization-plugin:
  admin-group: "camunda-admins"
  admin-user: "camunda-admin"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  show-actuator: true
  api-docs:
    path: /swagger/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    show-extensions: true

logging:
  level:
    org.zalando.logbook: INFO

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health/**

application:
  apifirst-server-jpa:
    protocol: "http"
    host: "localhost"
    port: "8085"
    context: "/"
