spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    hikari:
      username: camunda_ci
      password: ${camunda.db.password}
      registerMbeans: true
      schema: workflow_hello_world
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    url: jdbc:postgresql://swp74.swissperform.ch:5432/camunda_ci

server:
  servlet:
    context-path: /bpm
  port: 8081

camunda:
  bpm:
    admin-user:
      id: ldapbind-sit
      password: ${ldap.password}
    filter:
      create: All Tasks
    metrics:
      enabled: true
      db-reporter-activate: true
    generic-properties:
      properties:
        telemetry-reporter-activate: false

camunda-ldap-plugin:
  url: ldaps://ldaps.swpds.ch
  sslEnabled: false
  user: "CN=ldapbind-sit,OU=AADDC Users,DC=swpds,DC=ch"
  password: ${ldap.password}
  base-dn: "dc=swpds,dc=ch"
  users:
    user-search-base: "OU=AADDC Users"
    user-search-filter: "(&(objectClass=person)(objectClass=user)(!(cn=*EXT))(!(cn=adm*))(!(cn=zoom*))(!(cn=test*))(!(cn=zoom*))(!(cn=test*))(sAMAccountName=*))"
    user-id-attribute: sAMAccountName
    user-firstname-attribute: givenName
    user-lastname-attribute: sn
    user-email-attribute: mail
    user-password-attribute: userpassword
  groups:
    group-search-base: "OU=AADDC Users"
    group-search-filter: "(&(objectclass=group)(!(cn=SAG*)))"
    group-id-attribute: "cn"
    group-name-attribute: "name"
    group-member-attribute: "memberOf"
camunda-authorization-plugin:
  admin-group: "SWP-IT"
  admin-user: "ldapbind-sit"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  config: "classpath:logging/log4j2-ci.xml"

springdoc:
  show-actuator: true
  api-docs:
    path: /swagger/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    show-extensions: true

application:
  jtt:
    protocol: "http"
    host: "192.168.3.47"
    port: "8080"
    context: "swp-jtt"
