# Those values are set by Maven filtering
# and will be replaced with a valid version number during the build process.
apiVersion: v2
name: @project.artifactId@
description: A Helm chart for Spring 6 Project
type: application
version: @helm.chart.version@
appVersion: @project.version@

dependencies:
  - name: workflow-hello-world-ldap
    version: @helm.chart.version@
    repository: file://charts/ldap
    condition: ldap.enabled