---
apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: @project.artifactId@

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      initContainers:
        - name: wait-for-ldap
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z ldap 389; do echo "Waiting for LDAP..."; sleep 3; done; echo "LDAP is now accessible!"; exit 0' ]
        - name: wait-for-apifirst-server-jpa
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z apifirst-server-jpa 8082; do echo "[busybox: wait-for-apifirst-server-jpa] waiting for apifirst-server-jpa"; sleep 2; done; echo "[busybox: wait-for-apifirst-server-jpa] apifirst-server-jpa is available"' ]
      containers:
        - name: @project.artifactId@
          image: @docker.repo@/@project.artifactId@:@project.version@
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: CAMUNDA_LDAP_PLUGIN_URL
              value: ldap://ldap:389

            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true,
                  "logging.level.org.camunda.bpm.engine.jobexecutor": "INFO",
                  "logging.level.org.springframework.boot": "INFO",
                  "docker.compose.enabled": false
                }
          ports:
            - name: http
              containerPort: 8081
          startupProbe:
            httpGet:
              path: /bpm/actuator/health
              port: http
            initialDelaySeconds: 30
            failureThreshold: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /bpm/actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /bpm/actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
