---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  type: NodePort
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30389
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: bitnamilegacy/openldap:2.6.10
          ports:
            - containerPort: 389
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: LDAP_LOGLEVEL
              value: "stats"
            - name: LDAP_CONFIG_ADMIN_ENABLED
              value: "true"
            - name: LDAP_CONFIG_ADMIN_USERNAME
              value: "config-admin"
            - name: LDAP_CONFIG_ADMIN_PASSWORD
              value: "config-password"
            - name: LDAP_ROOT
              value: "dc=example,dc=ch"
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              value: "password"
            - name: LDAP_PORT_NUMBER
              value: "389"
            - name: LDAP_CUSTOM_LDIF_DIR
              value: "/ldifs"
          volumeMounts:
            - name: ldifs
              mountPath: /ldifs
          readinessProbe:
            exec:
              command:
                - ldapsearch
                - -x
                - -H
                - ldap://localhost:389
                - -D
                - cn=admin,dc=example,dc=ch
                - -w
                - password
                - -b
                - dc=example,dc=ch
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - ldapsearch
                - -x
                - -H
                - ldap://localhost:389
                - -D
                - cn=admin,dc=example,dc=ch
                - -w
                - password
                - -b
                - dc=example,dc=ch
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: ldifs
          configMap:
            name: ldap-config
