---
apiVersion: v1
kind: Service
metadata:
  name: workflow-hello-world
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: workflow-hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-hello-world
  labels:
    app: workflow-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-hello-world
  template:
    metadata:
      labels:
        app: workflow-hello-world
    spec:
      initContainers:
        - name: wait-for-ldap
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z ldap 389; do echo "Waiting for LDAP..."; sleep 3; done; echo "LDAP is now accessible!"; exit 0' ]
      containers:
        - name: workflow-hello-world
          image: domboeckli/workflow-hello-world:1.0.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: CAMUNDA_LDAP_PLUGIN_URL
              value: ldap://ldap:389
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true,
                  "logging.level.org.camunda.bpm.engine.jobexecutor": "INFO",
                  "logging.level.org.springframework.boot": "INFO",
                  "docker.compose.enabled": false
                }
          ports:
            - name: http
              containerPort: 8081
          startupProbe:
            httpGet:
              path: /bpm/actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /bpm/actuator/health/readiness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /bpm/actuator/health/liveness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
