###
GET {{host}}/{{context}}/engine-rest/engine
Accept: application/json

###
GET {{host}}/{{context}}/engine-rest/process-definition
Accept: application/json
Authorization: Basic {{username}} {{password}}

### gleich wie oben, aber mit engine name default
GET {{host}}/{{context}}/engine-rest/engine/default/process-definition
Accept: application/json
Authorization: Basic {{username}} {{password}}

### Start a new process instance
POST {{host}}/{{context}}/engine-rest/process-definition/key/hello-world-process/start
Accept: application/json
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "variables": {
        "input": {
            "value": "hello world",
            "type": "String"
        }
    },
    "businessKey": "myBusinessKey"
}

### Start a new process instance. shoud fail. missing input variable
POST {{host}}/{{context}}/engine-rest/process-definition/key/hello-world-process/start
Accept: application/json
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "variables": {
        "gugus": {
            "value": "hello world",
            "type": "String"
        }
    },
    "businessKey": "myBusinessKey"
}